<#
.SYNOPSIS
    Read-only dry run: regenerable build artefacts under project roots (Unreal / Visual Studio) with sizes.
.DESCRIPTION
    Finds Intermediate, .vs, DerivedDataCache and the safe sub-folders of Saved (StagedBuilds, Cooked,
    Logs, Crashes, Backup). Saved\Config, Saved\Autosaves and Saved\SaveGames are never listed. Nested
    matches are collapsed to their outermost folder. The output is a proposal for the owner: this script
    never deletes (OSF-INV-001); the owner removes approved targets with their own command.
.PARAMETER Roots
    Project roots to sweep. Installed engines should NOT be passed (or excluded with -Exclude).
.EXAMPLE
    .\Get-BuildArtifactCandidates.ps1 -Roots S:\Projects, D:\Projects -Exclude 'S:\UE_Vanilla\*'
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string[]]$Roots,
    [string[]]$Exclude = @(),
    [string[]]$Names = @('Intermediate', '.vs', 'DerivedDataCache'),
    [string[]]$SavedSubfolders = @('StagedBuilds', 'Cooked', 'Logs', 'Crashes', 'Backup'),
    [int]$MaxDepth = 6
)
$ErrorActionPreference = 'SilentlyContinue'
function Size([string]$p) { $s = 0L; try { foreach ($f in [IO.Directory]::EnumerateFiles($p, '*', 'AllDirectories')) { try { $s += ([IO.FileInfo]$f).Length } catch {} } } catch {}; $s }

$targets = foreach ($r in $Roots) {
    if (-not (Test-Path $r)) { continue }
    Get-ChildItem $r -Recurse -Directory -Force -Depth $MaxDepth -Attributes !ReparsePoint | Where-Object {
        ($Names -contains $_.Name) -or ($_.Parent.Name -eq 'Saved' -and $SavedSubfolders -contains $_.Name)
    } | Select-Object -ExpandProperty FullName
}
$targets = $targets | Where-Object { $t = $_; -not ($Exclude | Where-Object { $t -like $_ }) } | Sort-Object -Unique
$targets = $targets | Where-Object { $t = $_; -not ($targets | Where-Object { $_ -ne $t -and $t.StartsWith($_ + '\') }) }

$total = 0L
$rows = foreach ($t in $targets) { $s = Size $t; $total += $s; [pscustomobject]@{ GB = [math]::Round($s/1GB, 2); Path = $t } }
'== BUILD ARTEFACT CANDIDATES (dry run, nothing removed) =='
$rows | Sort-Object GB -Descending | ForEach-Object { '{0,8:N1} GB  {1}' -f $_.GB, $_.Path }
'{0} folders, {1:N1} GB. Regenerated by the next build/cook; removal is an owner action.' -f ($rows | Measure-Object).Count, ($total/1GB)
